services:

  # Reverse proxy
  traefik:
    image: traefik:v2.6.2
    container_name: traefik
    restart: always
    depends_on:
      - vocbench
      - showvoc
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./logs:/logs"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      # Logs configuration
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.filepath=/logs/access.log"
      # Docker provider
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # HTTP => HTTPS redirection
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      # HTTPS certificate generation
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tech@data-players.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory" # temp: migration 20241114 (imbrou)

  showvoc:
    image: "showvoc:${SV_VERSION}"
    container_name: showvoc
    build:
      context: "${SV_CLONE_DIR}/${SV_VERSION}"
    restart: always
    volumes:
      - "./volumes/showvoc/data:/opt/showvoc/data"
    ports:
      - "1980:1983"
    environment:
      JAVA_MAX_MEM: 1024M
      JAVA_MIN_MEM: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.showvoc.rule=Host(`${SV_DOMAIN}`)"
      - "traefik.http.routers.showvoc.entrypoints=websecure"
      - "traefik.http.routers.showvoc.tls.certresolver=myresolver"
      # Redirect from showvoc.datafoodconsortium.org
      - "traefik.http.middlewares.showvoc-from-fr.redirectregex.regex=^https?://showvoc\\.datafoodconsortium\\.org(.*)"
      - "traefik.http.middlewares.showvoc-from-fr.redirectregex.replacement=https://${SV_DOMAIN}$$1"
      - "traefik.http.middlewares.showvoc-from-fr.redirectregex.permanent=true"
      - "traefik.http.routers.showvoc-fr.rule=Host(`showvoc.datafoodconsortium.org`)"
      - "traefik.http.routers.showvoc-fr.middlewares=showvoc-from-fr"
      - "traefik.http.routers.showvoc-fr.entrypoints=websecure"
#     - "traefik.http.routers.showvoc-fr.tls=true"
#     - "traefik.http.routers.showvoc-fr.tls.certresolver=myresolver"
#     TODO: Migrate DNS, then uncomment and test.

  vocbench:
    image: "vocbench3:${VB_VERSION}"
    container_name: vocbench
    restart: always
    build:
      context: "${VB_CLONE_DIR}/${VB_VERSION}"
      args:
        vb_version: "${VB_VERSION}"
        st_version: "${ST_VERSION}"
    depends_on:
      - vocbench-graphdb
    ports:
      - "1979:1979"
    volumes:
      - ./volumes/vocbench/stdata:/opt/vocbench3/data
    environment:
      JAVA_MAX_MEM: 1024M
      JAVA_MIN_MEM: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vocbench.rule=Host(`${VB_DOMAIN}`)"
      - "traefik.http.routers.vocbench.entrypoints=websecure"
      - "traefik.http.routers.vocbench.tls.certresolver=myresolver"
      # Redirect from vocbench.datafoodconsortium.org
      - "traefik.http.middlewares.vocbench-from-fr.redirectregex.regex=^https?://vocbench\\.datafoodconsortium\\.org(.*)"
      - "traefik.http.middlewares.vocbench-from-fr.redirectregex.replacement=https://${VB_DOMAIN}$$1"
      - "traefik.http.middlewares.vocbench-from-fr.redirectregex.permanent=true"
      - "traefik.http.routers.vocbench-fr.rule=Host(`vocbench.datafoodconsortium.org`)"
      - "traefik.http.routers.vocbench-fr.middlewares=vocbench-from-fr"
      - "traefik.http.routers.vocbench-fr.entrypoints=websecure"
#     - "traefik.http.routers.vocbench-fr.tls=true"
#     - "traefik.http.routers.vocbench-fr.tls.certresolver=myresolver"
#     TODO: Migrate DNS, then uncomment and test.

  vocbench-graphdb:
    image: "graphdb-with-st-sails:${GDB_VERSION}"
    container_name: vocbench-graphdb
    restart: always
    build:
      context: "${VB_CLONE_DIR}/helpers/graphdb-with-st-sails"
      args:
        vb_version: "${VB_VERSION}"
        st_version: "${ST_VERSION}"
        gdb_version: "${GDB_VERSION}"
    ports:
      - "127.0.0.1:7200:7200"
    volumes:
      - ./volumes/vocbench-graphdb/gdbhome:/opt/graphdb/home
    environment:
      GDB_MAX_MEM: 4096M
      GDB_MIN_MEM: 1024M

